export const demoMockUsers: Record<string, any> = {
  super_admin: {
    id: "1",
    user_code: "SA001",
    email: "superadmin@cbtplatform.com",
    role: "super_admin",
    school_id: "",
    must_change_password: false,
    first_name: "Super",
    last_name: "Admin",
    school: { name: "CBT Platform", logo_url: "", primary_color: "#167d1c", accent_color: "#ff9001" },
  },
  school_admin: {
    id: "2",
    user_code: "AD001",
    email: "admin@greenfield.edu",
    role: "school_admin",
    school_id: "school-1",
    must_change_password: false,
    first_name: "Sarah",
    last_name: "Johnson",
    school: { name: "Greenfield Academy", logo_url: "", primary_color: "#167d1c", accent_color: "#ff9001" },
  },
  teacher: {
    id: "3",
    user_code: "TC001",
    email: "john.teacher@greenfield.edu",
    role: "teacher",
    school_id: "school-1",
    must_change_password: false,
    first_name: "John",
    last_name: "Williams",
    school: { name: "Greenfield Academy", logo_url: "", primary_color: "#167d1c", accent_color: "#ff9001" },
  },
  invigilator: {
    id: "4",
    user_code: "IV001",
    email: "jane.monitor@greenfield.edu",
    role: "invigilator",
    school_id: "school-1",
    must_change_password: false,
    first_name: "Jane",
    last_name: "Martinez",
    school: { name: "Greenfield Academy", logo_url: "", primary_color: "#167d1c", accent_color: "#ff9001" },
  },
  student: {
    id: "5",
    user_code: "ST001",
    email: "james.student@greenfield.edu",
    role: "student",
    school_id: "school-1",
    must_change_password: false,
    first_name: "James",
    last_name: "Anderson",
    school: { name: "Greenfield Academy", logo_url: "", primary_color: "#167d1c", accent_color: "#ff9001" },
  },
}

// Mock data for teacher dashboard
export const teacherMock = {
  exams: [
    {
      id: "exam-1",
      name: "Mathematics Mid-Term Exam",
      subject_name: "Mathematics",
      class_name: "SS3A",
      status: "PUBLISHED",
      question_count: 50,
      duration_minutes: 90,
      scheduled_at: "2026-04-28T10:00:00Z",
      created_at: "2026-04-20T08:00:00Z",
      pass_mark: 50,
    },
    {
      id: "exam-2",
      name: "English Language Quiz",
      subject_name: "English Language",
      class_name: "SS3A",
      status: "DRAFT",
      question_count: 30,
      duration_minutes: 60,
      scheduled_at: null,
      created_at: "2026-04-22T14:00:00Z",
      pass_mark: 50,
    },
    {
      id: "exam-3",
      name: "Physics Final Exam",
      subject_name: "Physics",
      class_name: "SS3B",
      status: "PENDING_APPROVAL",
      question_count: 60,
      duration_minutes: 120,
      scheduled_at: "2026-05-05T09:00:00Z",
      created_at: "2026-04-18T11:00:00Z",
      pass_mark: 50,
    },
  ],
  stats: {
    total_exams: 12,
    published: 8,
    draft: 3,
    pending: 1,
    total_questions: 450,
  },
}

// Mock data for student dashboard
export const studentMock = {
  exams: {
    assigned: [
      {
        id: "exam-1",
        name: "Mathematics Mid-Term Exam",
        subject_name: "Mathematics",
        class_name: "SS3A",
        status: "ACTIVE",
        question_count: 50,
        duration_minutes: 90,
        pass_mark: 50,
        starts_at: "2026-04-28T10:00:00Z",
        ends_at: "2026-04-28T11:30:00Z",
        session: null,
        result: null,
        retake_status: null,
      },
      {
        id: "exam-2",
        name: "English Language Quiz",
        subject_name: "English Language",
        class_name: "SS3A",
        status: "ACTIVE",
        question_count: 30,
        duration_minutes: 60,
        pass_mark: 50,
        starts_at: "2026-04-30T09:00:00Z",
        ends_at: "2026-04-30T10:00:00Z",
        session: null,
        result: null,
        retake_status: null,
      },
      {
        id: "exam-3",
        name: "Chemistry Test",
        subject_name: "Chemistry",
        class_name: "SS3A",
        status: "COMPLETED",
        question_count: 40,
        duration_minutes: 75,
        pass_mark: 50,
        starts_at: "2026-04-20T14:00:00Z",
        ends_at: "2026-04-20T15:15:00Z",
        session: { status: "SUBMITTED" },
        result: { result_status: "RELEASED", percentage: 78, pass_fail: "PASS" },
        retake_status: null,
      },
    ],
    paused: null,
    retake_approved: null,
  },
  results: [
    {
      id: "result-1",
      exam_name: "Chemistry Test",
      subject_name: "Chemistry",
      percentage: 78,
      pass_fail: "PASS",
      submitted_at: "2026-04-20T15:15:00Z",
      is_retake: false,
      superseded: false,
    },
    {
      id: "result-2",
      exam_name: "Biology Quiz",
      subject_name: "Biology",
      percentage: 91,
      pass_fail: "PASS",
      submitted_at: "2026-04-18T11:30:00Z",
      is_retake: false,
      superseded: false,
    },
    {
      id: "result-3",
      exam_name: "Economics Test",
      subject_name: "Economics",
      percentage: 45,
      pass_fail: "FAIL",
      submitted_at: "2026-04-15T16:00:00Z",
      is_retake: false,
      superseded: false,
    },
  ],
}

// Mock data for school admin
export const adminMock = {
  users: [
    { id: "1", name: "John Williams", role: "teacher", email: "john.teacher@greenfield.edu", status: "active" },
    { id: "2", name: "Jane Martinez", role: "invigilator", email: "jane.monitor@greenfield.edu", status: "active" },
    { id: "3", name: "James Anderson", role: "student", email: "james.student@greenfield.edu", status: "active" },
  ],
  exams_pending: [
    { id: "exam-3", name: "Physics Final Exam", teacher: "John Williams", submitted_at: "2026-04-18T11:00:00Z" },
  ],
  stats: {
    total_students: 450,
    total_teachers: 35,
    total_exams: 120,
    active_exams: 8,
  },
}

// Mock data for super admin
export const superAdminMock = {
  analytics: {
    total_schools: 45,
    active_schools: 42,
    suspended_schools: 3,
    total_revenue: 12500000,
    monthly_revenue: 850000,
    total_users: 15000,
    total_exams: 5400,
  },
  schools: [
    {
      id: "school-1",
      name: "Greenfield Academy",
      subscription_status: "ACTIVE",
      plan: "PREMIUM",
      students_count: 450,
      teachers_count: 35,
      created_at: "2025-01-15T00:00:00Z",
    },
    {
      id: "school-2",
      name: "Sunrise High School",
      subscription_status: "ACTIVE",
      plan: "STANDARD",
      students_count: 320,
      teachers_count: 28,
      created_at: "2025-02-20T00:00:00Z",
    },
    {
      id: "school-3",
      name: "Oakwood College",
      subscription_status: "GRACE_PERIOD",
      plan: "PREMIUM",
      students_count: 580,
      teachers_count: 42,
      created_at: "2024-11-10T00:00:00Z",
    },
  ],
}

// Mock data for invigilator
export const invigilatorMock = {
  rooms: [
    {
      id: "room-1",
      exam_name: "Mathematics Mid-Term Exam",
      active_students: 45,
      total_students: 50,
      alerts_count: 2,
      status: "ACTIVE",
    },
  ],
  students: [
    {
      id: "student-1",
      name: "James Anderson",
      status: "ACTIVE",
      progress: 35,
      alerts: ["Tab switch detected"],
      last_activity: "2026-04-25T10:15:00Z",
    },
  ],
}